pragma Singleton

import QtQuick

QtObject {
    readonly property url alignCenter: "qrc:/icons/align-middle.svg"
    readonly property url alignJustify: "qrc:/icons/align-justify.svg"
    readonly property url alignLeft: "qrc:/icons/align-left.svg"
    readonly property url alignRight: "qrc:/icons/align-right.svg"
    readonly property url bold: "qrc:/icons/bold.svg"
    readonly property url chevronDown: "qrc:/icons/chevron-down.svg"
    readonly property url chevronLeft: "qrc:/icons/chevron-left.svg"
    readonly property url chevronRight: "qrc:/icons/chevron-right.svg"
    readonly property url chevronUp: "qrc:/icons/chevron-up.svg"
    readonly property url circle: "qrc:/icons/circle.svg"
    readonly property url close: "qrc:/icons/x.svg"
    readonly property url colourPicker: "qrc:/icons/palette.svg"
    readonly property url copy: "qrc:/icons/copy.svg"
    readonly property url cut: "qrc:/icons/cut.svg"
    readonly property url duplicate: "qrc:/icons/duplicate.svg"
    readonly property url eraser: "qrc:/icons/eraser.svg"
    readonly property url eraseWhole: "qrc:/icons/minus-circle.svg"
    readonly property url exportDocument: "qrc:/icons/export.svg"
    readonly property url fit: "qrc:/icons/expand.svg"
    readonly property url hand: "qrc:/icons/move.svg"
    readonly property url highlighter: "qrc:/icons/highlight.svg"
    readonly property url importDocument: "qrc:/icons/import.svg"
    readonly property url paste: "qrc:/icons/paste.svg"
    readonly property url pen: "qrc:/icons/pencil.svg"
    readonly property url italic: "qrc:/icons/italic.svg"
    readonly property url strikethrough: "qrc:/icons/strikethrough.svg"
    readonly property url straightLine: "qrc:/icons/minus.svg"
    readonly property url text: "qrc:/icons/text.svg"
    readonly property url underline: "qrc:/icons/underline.svg"
    readonly property url square: "qrc:/icons/square.svg"
    readonly property url plus: "qrc:/icons/plus.svg"
    readonly property url help: "qrc:/icons/help-circle.svg"
    readonly property url redo: "qrc:/icons/redo.svg"
    readonly property url save: "qrc:/icons/save.svg"
    readonly property url select: "qrc:/icons/pointer.svg"
    readonly property url selectAll: "qrc:/icons/select-multiple.svg"
    readonly property url turnLeft: "qrc:/icons/rotate-left.svg"
    readonly property url turnRight: "qrc:/icons/rotate-right.svg"
    readonly property url settings: "qrc:/icons/cog.svg"
    readonly property url shape: "qrc:/icons/shape-square.svg"
    readonly property url trash: "qrc:/icons/trash.svg"
    readonly property url undo: "qrc:/icons/undo.svg"
    readonly property url zoomIn: "qrc:/icons/zoom-in.svg"
    readonly property url zoomOut: "qrc:/icons/zoom-out.svg"
}
